accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('input-name/', views.name, name='name'),
    path('input-gender/', views.gender, name='gender'),
    path('input-birth/', views.birth, name='birth'),
    path('input-alarm/', views.alarm, name='alarm'),
    path('setting/', views.setting, name='setting'),
]

diaries/urls.py
from django.urls import path
from . import views

app_name = 'diaries'

urlpatterns = [
    path('loading/', views.loading, name='loading'),
    path('info/', views.info, name='info'),
    path('report/', views.report, name='report'),
    path('index/', views.index, name='index'),
]

mirinae/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/', include('diaries.urls')),
    path('accounts/', include('accounts.urls')),
    re_path('', include('pwa.urls')),
]

accounts/models.py
from django.db import models

class User(models.Model):
    name = models.TextField(default=False)
    gender = models.TextField()
    birth = models.DateField()
    # 오전이면 1, 오후면 +12시간 처리
    alarm = models.TimeField()
    # 1이면 로그인 된 상태, 디폴트는 0
    login = models.IntegerField(default=0)
    

diaries/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.
def name(request):
    return render(request, 'accounts/name.html')

def gender(request):
    return render(request, 'accounts/gender.html')

def birth(request):
    return render(request, 'accounts/birth.html')

def alarm(request):
    return render(request, 'accounts/alarm.html')

def setting(request):
    return render(request, 'accounts/setting.html')

diaries/views.py
from django.shortcuts import render

# Create your views here.
def loading(request):
    return render(request, 'diaries/loading.html')

def info(request):
    return render(request, 'diaries/info.html')

def report(request):
    return render(request, 'diaries/report.html')

def index(request):
    return render(request, 'diaries/index.html')

accounts/templates/accounts/alarm.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'diaries/css/base.css' %}">
{% endblock %}

{% block content %}

<!-- heart images -->
<div style="display:flex; justify-content:center; align-items:center; padding-top:3rem;">
    <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
    <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
    <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
    <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
</div>

<!-- text box -->
<div style="display:flex; justify-content:center; align-items:center; flex-direction:column;">
    <h1 class="text-center fw-light mt-5 mb-3" style="font-size:24px;">제가 언제 찾아갈까요?</h1>
    <p class="text-center fw-light" style="font-size:17px;">아래에서 시간을 정해주세요!</p>
</div>

{% comment %} <div class="row">
    <button type="button" class="btn" id=""><div class="align-content-xxl-between-6" value="0">오전</div></button>
    <button type="button" class="btn" id=""><div class="col-6" value="1">오후</div></button>
</div> {% endcomment %}

<!-- checkbox -->
<div class="input-group flex-nowrap" style="margin-top: 2rem;">
    <div style="display:flex; flex-direction:column;">
        <div style="display:flex">
            <input type="checkbox">
            <p style="margin:0; margin-left:0.5rem; font-size:18px;">(필수) 이용약관</p>
        </div>
        <div style="display:flex;">
            <input type="checkbox">
            <p style="margin:0; margin-left:0.5rem; font-size:18px;">(필수) 개인 정보 수집 / 이용 동의</p>
        </div>
    </div>
</div>

<!-- submit -->
<div style="height:2rem;"></div>
<a href="{% url 'diaries:index' %}">
    <input class="btn btn-dark" type="submit" value="확인" style="width:100%; height:4rem; font-size:25px;">
</a>

{% endblock %}

accounts/templates/accounts/birth.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- heart images -->
<div style="display:flex; justify-content:center; align-items:center; padding-top:3rem;">
  <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
  <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
  <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
  <img src="{% static 'diaries/image/bin-heart.png' %}" alt="" style="height:2rem;">
</div>

<h1 class="text-center fw-light my-5" style="font-size:24px;">생년월일을 입력해 주세요.</h1>
<!-- <h3 class="text-center" style="margin-top: 10rem;">1960년 10월 17일</h3> -->

<!-- birth input -->
<div style="height:2rem;"></div>
<form method="">
<div class="input-group flex-nowrap">
  <span class="input-group-text" id="addon-wrapping">생년월일</span>
  <input type="date" class="form-control" placeholder="birth" aria-label="birth" aria-describedby="addon-wrapping">
</div>

<!-- next button -->
<div class="d-flex justify-content-end position-fixed" style="bottom: 12rem; right: 3rem;">
  <a class="btn btn-lg btn-outline-dark" href="{% url 'accounts:alarm' %}">다음</a>
</div>
{% endblock %}

accounts/templates/accounts/gender.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}

<!-- heart images -->
<div style="display:flex; justify-content:center; align-items:center; padding-top:3rem;">
  <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
  <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
  <img src="{% static 'diaries/image/bin-heart.png' %}" alt="" style="height:2rem;">
  <img src="{% static 'diaries/image/bin-heart.png' %}" alt="" style="height:2rem;">
</div>

<!-- text box -->
<h1 class="text-center fw-light my-5" style="font-size:24px;">성별을 입력해 주세요.</h1>

<!-- gender input -->
<div style="height:2rem;"></div>
<div class="text-center">
<input class="form-check-input mx-2" type="radio" name ="gender" value="man">남
<input class="form-check-input mx-2" type="radio" name ="gender" value="woman">여
</div>

<!-- next button -->
<div class="d-flex justify-content-end position-fixed" style="bottom: 12rem; right: 3rem;">
  <a class="btn btn-lg btn-outline-dark" href="{% url 'accounts:birth' %}">다음</a>
</div>

{% endblock %}

accounts/templates/accounts/name.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}

<!-- heart images -->
<div style="display:flex; justify-content:center; align-items:center; padding-top:3rem;">
  <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
  <img src="{% static 'diaries/image/bin-heart.png' %}" alt="" style="height:2rem;">
  <img src="{% static 'diaries/image/bin-heart.png' %}" alt="" style="height:2rem;">
  <img src="{% static 'diaries/image/bin-heart.png' %}" alt="" style="height:2rem;">
</div>

<!-- text box -->
<div style="display:flex; justify-content:center; align-items:center; flex-direction:column;">
  <h1 class="text-center fw-light mt-5 mb-3" style="font-size:24px;">이름을 입력해 주세요.</h1>
  <p class="text-center fw-light" style="font-size:17px;">손녀가 입력한 이름으로 불러드릴게요.</p>
</div>

<!-- name input -->
<div style="height:2rem;"></div>
<input class="form-control" type="text" size="7" maxlength = "6" minlength = "2" placeholder = "이름을 입력해주세요!">

<!-- next button -->
<div class="d-flex justify-content-end position-fixed" style="bottom: 12rem; right: 3rem;">
  <a class="btn btn-lg btn-outline-dark" href="{% url 'accounts:gender' %}">다음</a>
</div>


{% endblock %}

accounts/templates/accounts/setting.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
<div style="display:flex; justify-content:center; align-items:center; flex-direction: column; height: 70%;">
  <div style="margin-top: 2rem;">
    <h1 class="fw-light" style="margin-bottom: 2.5rem;">환경설정</h1>
  </div>
  <div class="container text-center">
    <div class="row g-3">
      <div class="col-6">
        <div class="p-3 rounded-3 bg-white" style="height: 8rem; box-shadow: 3px 5px 8px 3px rgba(0, 0, 0, 0.08);">
          <svg xmlns="http://www.w3.org/2000/svg" width="4rem" height="4rem" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16" style="color: #f794a3;">
            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
          </svg>
            <p class="card-title mt-1">이름 설정</p>
        </div>
      </div>
      <div class="col-6">
        <div class="p-3 rounded-3 bg-white d-flex flex-column align-items-center justify-content-center" style="height: 8rem; box-shadow: 3px 5px 8px 3px rgba(0, 0, 0, 0.08);">
          <svg xmlns="http://www.w3.org/2000/svg" width="3.7rem" height="3.7rem" fill="currentColor" class="bi bi-gender-ambiguous" viewBox="0 0 16 16" style="color:#f794a3;">
            <path fill-rule="evenodd" d="M11.5 1a.5.5 0 0 1 0-1h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V1.707l-3.45 3.45A4 4 0 0 1 8.5 10.97V13H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V14H6a.5.5 0 0 1 0-1h1.5v-2.03a4 4 0 1 1 3.471-6.648L14.293 1H11.5zm-.997 4.346a3 3 0 1 0-5.006 3.309 3 3 0 0 0 5.006-3.31z"/>
          </svg>
            <p class="card-title mt-2">성별 설정</p>
        </div>
      </div>
      <div class="col-6">
        <div class="p-3 rounded-3 bg-white d-flex flex-column align-items-center justify-content-center" style="height: 8rem; box-shadow: 3px 5px 8px 3px rgba(0, 0, 0, 0.08);">
          <svg xmlns="http://www.w3.org/2000/svg" width="3.3rem" height="3.3rem" fill="currentColor" class="bi bi-calendar-check" viewBox="0 0 16 16" style="color:#f794a3;">
            <path d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
            <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
          </svg>
            <p class="card-title mt-2">생일 설정</p>

        </div>
      </div>
      <div class="col-6">
        <div class="p-3 rounded-3 bg-white d-flex flex-column align-items-center justify-content-center" style="height: 8rem; box-shadow: 3px 5px 8px 3px rgba(0, 0, 0, 0.08);">
          <svg xmlns="http://www.w3.org/2000/svg" width="3rem" height="3rem" fill="currentColor" class="bi bi-alarm-fill" viewBox="0 0 16 16" style="color:#f794a3;">
            <path d="M6 .5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1H9v1.07a7.001 7.001 0 0 1 3.274 12.474l.601.602a.5.5 0 0 1-.707.708l-.746-.746A6.97 6.97 0 0 1 8 16a6.97 6.97 0 0 1-3.422-.892l-.746.746a.5.5 0 0 1-.707-.708l.602-.602A7.001 7.001 0 0 1 7 2.07V1h-.5A.5.5 0 0 1 6 .5zm2.5 5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5zM.86 5.387A2.5 2.5 0 1 1 4.387 1.86 8.035 8.035 0 0 0 .86 5.387zM11.613 1.86a2.5 2.5 0 1 1 3.527 3.527 8.035 8.035 0 0 0-3.527-3.527z"/>
          </svg>
            <p class="card-title" style="margin-top: 0.7rem;">알람 설정</p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/volume.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'diaries/css/base.css' %}">
{% endblock %}

{% block content %}

<!-- heart images -->
<div style="display:flex; justify-content:center; align-items:center; padding-top:3rem;">
    <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
    <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
    <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
    <img src="{% static 'diaries/image/full-heart.png' %}" alt="" style="height:2rem;">
</div>

<!-- text box -->
<div style="display:flex; justify-content:center; align-items:center; flex-direction:column;">
    <h1 class="text-center fw-light mt-5 mb-3" style="font-size:24px;">소리 크기를 설정해 주세요.</h1>
    <p class="text-center fw-light" style="font-size:17px;">해당 소리로 알림이 옵니다.</p>
</div>

<!-- volume box -->
<i class="bi bi-megaphone"></i>

<div style="display:flex; justify-content:center; align-items:center;" >
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-megaphone" viewBox="0 0 16 16">
        <path d="M13 2.5a1.5 1.5 0 0 1 3 0v11a1.5 1.5 0 0 1-3 0v-.214c-2.162-1.241-4.49-1.843-6.912-2.083l.405 2.712A1 1 0 0 1 5.51 15.1h-.548a1 1 0 0 1-.916-.599l-1.85-3.49a68.14 68.14 0 0 0-.202-.003A2.014 2.014 0 0 1 0 9V7a2.02 2.02 0 0 1 1.992-2.013 74.663 74.663 0 0 0 2.483-.075c3.043-.154 6.148-.849 8.525-2.199V2.5zm1 0v11a.5.5 0 0 0 1 0v-11a.5.5 0 0 0-1 0zm-1 1.35c-2.344 1.205-5.209 1.842-8 2.033v4.233c.18.01.359.022.537.036 2.568.189 5.093.744 7.463 1.993V3.85zm-9 6.215v-4.13a95.09 95.09 0 0 1-1.992.052A1.02 1.02 0 0 0 1 7v2c0 .55.448 1.002 1.006 1.009A60.49 60.49 0 0 1 4 10.065zm-.657.975 1.609 3.037.01.024h.548l-.002-.014-.443-2.966a68.019 68.019 0 0 0-1.722-.082z"/>
    </svg>
</div>

<div style="height:2rem;"></div>
<select class="form-select" size="3" aria-label="size 3 select example">
    <option selected>
        소리 크기를 설정해 주세요.
    </option>
    <option value="1">작게</option>
    <option value="2">보통으로</option>
    <option value="3">크게</option>
</select>

<!-- checkbox -->
<div class="input-group flex-nowrap" style="margin-top: 2rem;">
    <div style="display:flex; flex-direction:column;">
        <div style="display:flex">
            <input type="checkbox">
            <p style="margin:0; margin-left:0.5rem; font-size:18px;">(필수) 이용약관</p>
        </div>
        <div style="display:flex;">
            <input type="checkbox">
            <p style="margin:0; margin-left:0.5rem; font-size:18px;">(필수) 개인 정보 수집 / 이용 동의</p>
        </div>
    </div>
</div>

<!-- submit -->
<div style="height:5rem;"></div>
<input class="btn btn-dark" type="submit" value="확인" style="width:100%; height:3rem; font-size:20px;">




{% endblock %}

diaries/templates/diaries/index.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'diaries/css/base.css' %}">
{% endblock %}

{% block content %}

<!-- space -->
<div style="height:5rem;"></div>

<!-- question box -->
<h1 class="question-title">오늘의 질문</h1>
<div class="question-box">
    <p class="question-text">오늘 뭐 드시고 싶으세요?</p>
</div>

<!-- nav bar -->
<div class="fixed-bottom bg-light nav-box">
    <a href=""><img class="nav-img" src="{% static 'diaries/image/report.png' %}" alt=""></a>
    <a href="{% url 'diaries:index' %}"><img class="nav-img" src="{% static 'diaries/image/home.png' %}" alt=""></a>
    <a href="{% url 'accounts:setting' %}"><img class="nav-img" src="{% static 'diaries/image/settings.png' %}" alt=""></a>
</div>

{% endblock %}

diaries/templates/diaries/info.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'diaries/css/style.css' %}">
{% endblock %}
<script type="text/javascript" src ="{% static 'diaries/js/script.js' %}"></script>

{% block content %}
<h1 class="info-text fw-light" style="font-size: 20px; padding-top: 4rem; line-height: 3rem;">
  <div class="c1">
    <div class="type">안녕하세요</div></div>
  </br>
  <div class="c2">
    <div class="type2">저는 매일 찾아오는</div></div>
  </br>
  <div class="c3">
    <div class="type3"><span class="fw-normal" style="color: rgb(242, 131, 179);">손녀</span>에요</div></div>
  </br>
  <div class="c4">
    <div class="type4">만나서 반가워요!</div></div>
  </br>
</h1>

<!-- next button -->
<div class="d-flex justify-content-end position-fixed" style="bottom: 12rem; right: 3rem;">
  <a class="btn btn-lg btn-outline-dark" href="{% url 'accounts:name' %}">다음</a>
</div>
{% endblock %}

diaries/templates/diaries/loading.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="c1">
  <div class="type">
  <div class="logo text-center" style="padding: 15rem 0 15rem;">
    <a href="{% url 'diaries:info' %}">
      <img src="{% static 'images/logo.png' %}" alt="logo-image" style="width: 15rem;">
    </a>
  </div>
</div>
</div>
{% endblock %}

diaries/templates/diaries/report.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- 리포트 헤더 -->
<div class="mt-5">
  <h1 class="fw-light" style="line-height: 2.5rem;"><span class="fw-normal">권세빈</span> 할머니는<br>이번 <span class="fw-normal">10월달에</span><br><span class="fw-semibold text-primary">굉장히 긍정적</span>이셨네요!</h1>
  </h1>
</div>

<!-- 하트 -->
<div class="">
  <div class="text-center top-50 mb-3" style="margin-top: 6rem; z-index: 3px;">
    <img src="{% static 'diaries/image/positive.png' %}" style="width: 5rem;">
  </div>
  <!-- 그래프 -->
  <div class="progress">
    <div class="progress-bar bg-warning" role="progressbar" aria-label="Warning example" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
</div>
{% endblock %}

templates/base.html
{% load pwa %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    {% progressive_web_app_meta %}
    {% block css %}
    {% endblock %}
    <title>Mirinae</title>
</head>
    <div class="container mt-5 px-5 position-fixed" style="height: 100vh; overflow: hidden;">
        {% block content %}
        {% endblock %}
    </div>

    <!-- nav bar -->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>